export const products = [
	{
		id: 1,
		title: 'Мужские Кроссовки Nike Blazer Mid Suede',
		price: 1299900,
		imageUrl: '/sneakers/sneakers-1.jpg',
	},
	{
		id: 2,
		title: 'Мужские Кроссовки Nike Air Max 270',
		price: 1560000,
		imageUrl: '/sneakers/sneakers-2.jpg',
		isFavorite: true,
		favoriteId: 1,
	},
	{
		id: 3,
		title: 'Мужские Кроссовки Nike Blazer Mid Suede',
		price: 849900,
		imageUrl: '/sneakers/sneakers-3.jpg',
		isFavorite: true,
		favoriteId: 2,
	},
	{
		id: 4,
		title: 'Кроссовки Puma X Aka Boku Future Rider',
		price: 780000,
		imageUrl: '/sneakers/sneakers-4.jpg',
		isFavorite: false,
		favoriteId: null,
	},
	{
		id: 5,
		title: 'Кроссовки Future Rider',
		price: 955000,
		imageUrl: '/sneakers/sneakers-5.jpg',
		isFavorite: false,
		favoriteId: null,
	},
	{
		id: 6,
		title: 'Кроссовки Black Edition',
		price: 1699900,
		imageUrl: '/sneakers/sneakers-6.jpg',
		isFavorite: false,
		favoriteId: null,
	},
	{
		id: 7,
		title: 'Кроссовки Orange Boomb Edition',
		price: 749900,
		imageUrl: '/sneakers/sneakers-7.jpg',
		isFavorite: false,
		favoriteId: null,
	},
	{
		id: 8,
		title: 'Кроссовки Nike Air Max 270',
		price: 1560000,
		imageUrl: '/sneakers/sneakers-8.jpg',
		isFavorite: false,
		favoriteId: null,
	},
	{
		id: 9,
		title: 'Кроссовки Nike Air Force 1',
		price: 590000,
		imageUrl: '/sneakers/sneakers-9.jpg',
		isFavorite: false,
		favoriteId: null,
	},
	{
		id: 10,
		title: 'Кроссовки Adidas Ultraboost',
		price: 1150000,
		imageUrl: '/sneakers/sneakers-10.jpg',
		isFavorite: false,
		favoriteId: null,
	},
	{
		id: 11,
		title: 'Кроссовки Puma Clyde All-Pro',
		price: 760000,
		imageUrl: '/sneakers/sneakers-11.jpg',
		isFavorite: false,
		favoriteId: null,
	},
	{
		id: 12,
		title: 'Кроссовки Converse Chuck Taylor All-Star',
		price: 1300000,
		imageUrl: '/sneakers/sneakers-12.jpg',
		isFavorite: false,
		favoriteId: null,
	},
]
