import { ThemeProvider } from '@/features/theme/theme-provider'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Duckers Tech Project && Sneakers Store',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body>
				<AppRouterCacheProvider>
					<ThemeProvider>{children}</ThemeProvider>
				</AppRouterCacheProvider>
			</body>
		</html>
	)
}
