import type { Metadata } from 'next'
import { AppProvider } from './_providers/app-provider'

export const metadata: Metadata = {
	title: 'Duckers Tech Project && Sneakers Store',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body>
				<AppProvider>{children}</AppProvider>
			</body>
		</html>
	)
}
